# Generated by Django 3.2.5 on 2021-07-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMapp', '0003_auto_20210705_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Authors',
            new_name='authors',
        ),
    ]
