# Generated by Django 3.2.5 on 2021-07-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMapp', '0004_rename_authors_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(blank=True, to='LMapp.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='LMapp.Author'),
        ),
    ]
