# Generated by Django 3.2.5 on 2021-07-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMapp', '0005_auto_20210705_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='LMapp.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='LMapp.Author'),
        ),
    ]
